services:
  chatbot:
    build: .
    container_name: vision-one-mcp-chat
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    # Do NOT mount the source tree; it overwrites files & node_modules inside the image
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
